<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <gazebo reference="base_left_front_wheel_joint">
        <mu1 value="0.8"/>
        <mu2 value="0.8"/>
    </gazebo>
    <gazebo reference="base_left_rear_wheel_joint">
        <mu1 value="0.8"/>
        <mu2 value="0.8"/>
    </gazebo>
    <gazebo reference="base_right_front_wheel_joint">
        <mu1 value="0.8"/>
        <mu2 value="0.8"/>
    </gazebo>
    <gazebo reference="base_right_rear_wheel_joint">
        <mu1 value="0.8"/>
        <mu2 value="0.8"/>
    </gazebo>


    <gazebo>
        <plugin filename="gz-sim-diff-drive-system" 
                name="gz::sim::systems::DiffDrive">
                <left_joint>base_left_front_wheel_joint</left_joint>
                <left_joint>base_left_rear_wheel_joint</left_joint>
                <right_joint>base_right_front_wheel_joint</right_joint>
                <right_joint>base_right_rear_wheel_joint</right_joint>
                <wheel_separation>${car_width+wheel_length}</wheel_separation>
                <wheel_radius>${wheel_radius}</wheel_radius>
                <frame_id>odom</frame_id>
                <child_frame_id>base_footprint</child_frame_id>
        </plugin>
    </gazebo>

    <gazebo>
        <plugin filename="gz-sim-joint-state-publisher-system"
                name="gz::sim::systems::JointStatePublisher">
                <joint_name>base_left_front_wheel_joint</joint_name>
                <joint_name>base_left_rear_wheel_joint</joint_name>
                <joint_name>base_right_front_wheel_joint</joint_name>
                <joint_name>base_right_rear_wheel_joint</joint_name>
        </plugin>
    </gazebo>


    <gazebo reference="camera_link">
        <sensor name="camera" type="camera">
            <gz_frame_id>camera_optical_frame</gz_frame_id>
            <camera>
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                <near>0.1</near>
                <far>15</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
                <camera_info_topic>camera/camera_info</camera_info_topic>
            </camera>
            <always_on>1</always_on>
            <update_rate>20</update_rate>
            <visualize>true</visualize>
            <topic>camera/image_raw</topic>

        </sensor>

        <sensor name="rs_depth" type="depth_camera">
            <always_on>true</always_on>
            <update_rate>30</update_rate>
            <visualize>true</visualize>
            <topic>camera/depth/image</topic> 
            <gz_frame_id>camera_depth_optical_frame</gz_frame_id>  
            <camera>
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>360</height>
                    <format>R_FLOAT32</format>  
                </image>
                <clip>
                    <near>0.1</near>
                    <far>15</far>
                </clip>
                <camera_info_topic>camera/depth/camera_info</camera_info_topic>
            </camera>
        </sensor>
    </gazebo>

    <gazebo reference="lidar_link">
        <sensor name="lidar" type="gpu_lidar">
            <pose>0 0 0 0 0 0</pose>
            <always_on>true</always_on>
            <visualize>true</visualize> <update_rate>120</update_rate>
            <topic>scan</topic>
            <gz_frame_id>lidar_link</gz_frame_id>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples> <resolution>1</resolution>
                        <min_angle>-3.14159</min_angle> <max_angle>3.14159</max_angle>  </horizontal>
                </scan>
                <range>
                    <min>0.10</min>
                    <max>20.0</max> <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
        </sensor>
    </gazebo>


        <gazebo reference="imu_link">
            <sensor name="imu_sensor" type="imu">
                <always_on>1</always_on>
                <update_rate>50</update_rate> <visualize>true</visualize>
                <topic>/imu</topic> <gz_frame_id>imu_link</gz_frame_id> </sensor>
        </gazebo>

</robot>


