<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="car_hight" value="0.3" />
    <xacro:property name="car_width" value="0.8" />
    <xacro:property name="car_length" value="1.0" />
    <xacro:property name="wheel_radius" value="0.2" />
    <xacro:property name="wheel_length" value="0.1" />

    <xacro:macro name="wheel_inertia" params="m r h o_xyz o_rpy">
        <inertial>
            <origin xyz="${o_xyz}" rpy="${o_rpy}"/>
            <mass value="${m}"/>
            <inertia
                ixx="${(1/12)*m*(3*r*r + h*h)}"
                ixy="0.0"
                ixz="0.0"
                iyy="${(1/12)*m*(3*r*r + h*h)}"
                iyz="0.0"
                izz="${(1/2)*m*r*r}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="box_inertia" params="m x y z o_xyz o_rpy">
        <inertial>
            <origin xyz="${o_xyz}" rpy="${o_rpy}"/>
            <mass value="${m}"/>
            <inertia
                ixx="${(m/12.0)*(y*y + z*z)}"
                ixy="0.0"
                ixz="0.0"
                iyy="${(m/12.0)*(x*x + z*z)}"
                iyz="0.0"
                izz="${(m/12.0)*(x*x + y*y)}" />
        </inertial>
    </xacro:macro>



    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
            <material name="black">
                <color rgba="0 0 0 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </link>


    <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/> <child link="lidar_link"/>
    <origin xyz="0 0 ${car_hight/2 + 0.02}" rpy="0 0 0"/> </joint>



    <link name="imu_link">
        <visual>
            <geometry>
                <box size="0.02 0.02 0.02"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.02 0.02 0.02"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.01"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </link>




    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0 0 0.1" rpy="0 0 0"/> \
    </joint>



    <link name="base_footprint" />
    
    <link name="base_link">
        <visual>
            <geometry>
               <box size="${car_length} ${car_width} ${car_hight}" /> 
               <!---<mesh filename="package://robot_description/meshes/car_base.dae" scale="1 1 1"/>-->
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="blue">
                <color rgba="0.196 0.890 0.808 1"/>  
            </material>
        </visual>
         <collision>
            <geometry>
                <box size="${car_length} ${car_width} ${car_hight}" />
            </geometry>
             <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5" x="${car_length}" y="${car_width}" 
                           z="${car_hight}" o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>


    <link name="camera_link">
        <visual>
            <geometry>
                <box size="0.15 0.3 0.08"/>
            </geometry>
            <material name="camera_black">
                <color rgba="0.1 0.1 0.1 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.15 0.3 0.08" />
            </geometry>
             <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="0.001" x="0.15" y="0.3" 
                           z="0.08" o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <link name="camera_optical_frame"/>
    <link name="camera_depth_optical_frame"/>
    
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" /> 
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="red">
                    <color rgba="0.588 0.647 0.890 1"/> 
                </material>
            </visual>
            <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" /> 
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </collision>
        <xacro:wheel_inertia m="0.05" r="${wheel_radius}" h="${wheel_length}" 
                             o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>
    
    <xacro:wheel_link prefix="left_front" />
    <xacro:wheel_link prefix="right_front" />
    <xacro:wheel_link prefix="left_rear" />
    <xacro:wheel_link prefix="right_rear" />



    
    <joint name="base_left_front_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_front_wheel_link" />
        <origin xyz="${(car_length / 4.0)} ${(car_width + wheel_length) / 2.0} ${-car_hight / 2.0}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <effort>600.0</effort>    <!--max siła przylozenia w [N·m] -->
        <velocity>100.0</velocity> <!-- max 100 [rad/s]  -->
    </joint>
    
    <joint name="base_right_front_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_front_wheel_link" />
        <origin xyz="${(car_length / 4.0) } ${-(car_width + wheel_length) / 2.0} ${-car_hight / 2.0}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <effort>600.0</effort>    <!--max siła przylozenia w [N·m] -->
        <velocity>100.0</velocity> <!-- max 100 [rad/s]  -->
    </joint>
    
    <joint name="base_left_rear_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_rear_wheel_link" />
        <origin xyz="${-car_length / 4.0 } ${(car_width + wheel_length) / 2.0} ${-car_hight / 2.0}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <effort>600.0</effort>    <!--max siła przylozenia w [N·m] -->
        <velocity>100.0</velocity> <!-- max 100 [rad/s]  -->
    </joint>
    
    <joint name="base_right_rear_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_rear_wheel_link" />
        <origin xyz="${-car_length / 4.0 } ${-(car_width + wheel_length) / 2.0} ${-car_hight / 2.0}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <effort>600.0</effort>    <!--max siła przylozenia w [N·m] -->
        <velocity>100.0</velocity> <!-- max 100 [rad/s]  -->
    </joint>
    
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius + car_hight/2.0}" rpy="0 0 0"/>
    </joint>

      <joint name="camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="${(car_length + 0.15)/2} 0 ${car_hight/2 - 0.05}" rpy="0 0 0"/>
    </joint>

    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_optical_frame"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <joint name="camera_depth_optical_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_depth_optical_frame"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>  
</joint>


</robot>